export const keyStrokes = [
  {
    id: "01",
    category: "General",
    task: "Show Command Palette",
    firstkey: "Ctrl",
    secondkey: "Shift",
    thirdkey: "P",
    alternatekey: "F1",
  },
  {
    id: "02",
    category: "General",
    task: "Quick Open, Go to File…",
    firstkey: "Ctrl",
    secondkey: "P",
    thirdkey: "None",
    alternatekey: "None",
  },
  {
    id: "03",
    category: "General",
    task: "New window / instance",
    firstkey: "Ctrl",
    secondkey: "Shift",
    thirdkey: "N",
    alternatekey: "None",
  },
  {
    id: "04",
    category: "General",
    task: "Close window / instance",
    firstkey: "Ctrl",
    secondkey: "Shift",
    thirdkey: "W",
    alternatekey: "None",
  },
  {
    id: "05",
    category: "General",
    task: "User settings",
    firstkey: "Ctrl",
    secondkey: ",",
    thirdkey: "None",
    alternatekey: "None",
  },
  {
    id: "06",
    category: "General",
    task: "Keyboard Shortcuts",
    firstkey: "Ctrl",
    secondkey: "K",
    thirdkey: "None",
    alternatekey: "None",
  },
];