export const keyStrokes = [{
    id: 0,
    category: "General",
    task: "Show Left",
    firstkey: {
      symbol: "Ctrl",
      code: 37,
    },
    secondkey: "",
    thirdkey: "",
    alternatekey: "",
  },
  {
    id: 1,
    category: "General",
    task: "Show Right",
    firstkey: {
      symbol: "Right",
      code: 39,
    },
    secondkey: "",
    thirdkey: "",
    alternatekey: "",
  },
  {
    id: 2,
    category: "General",
    task: "New window / instance",
    firstkey: 17,
    secondkey: 16,
    thirdkey: 80,
    alternatekey: "None",
  },
  // {
  //   id: "04",
  //   category: "General",
  //   task: "Close window / instance",
  //   firstkey: "Ctrl",
  //   secondkey: "Shift",
  //   thirdkey: "W",
  //   alternatekey: "None",
  // },
  // {
  //   id: "05",
  //   category: "General",
  //   task: "User settings",
  //   firstkey: "Ctrl",
  //   secondkey: ",",
  //   thirdkey: "None",
  //   alternatekey: "None",
  // },
  // {
  //   id: "06",
  //   category: "General",
  //   task: "Keyboard Shortcuts",
  //   firstkey: "Ctrl",
  //   secondkey: "K",
  //   thirdkey: "None",
  //   alternatekey: "None",
  // },
];